name: fine_stepper
description: A horizontal stepper that does the job just fine
version: 0.1.0+1
repository: https://github.com/michaelsoliman1/fine_stepper
issue_tracker: https://github.com/michaelsoliman1/fine_stepper/issues

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1
