name: main

on:
  pull_request:
    branches:
      - main

jobs:
  semantic_pull_request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Flutter action
        uses: subosito/flutter-action@v2.10.0

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format -l 105 --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze --no-pub

      - name: Run tests
        run: flutter test
